SRC = main.cpp polinomio/polinomio.cpp fraccion/fraccion.cpp matriz/matriz.cpp
CC = g++
CFLGAS = -Wall -o


all:
		$(CC) $(CFLGAS) labo3 $(SRC)

.PHONY: clean
clean:
		@echo Deleting files...
		rm labo3

run:
		./labo3
